all: p3 p4

p3: hw2_p3.cpp linkedlist.cpp linkedlist.h
	g++ -Wall -g -o p3 hw2_p3.cpp linkedlist.cpp linkedlist.h

p4: hw2_p4.cpp truthValues.cpp truthValues.h
	g++ -Wall -g -o p4 hw2_p4.cpp truthValues.cpp truthValues.h
